parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: 5432
    database_name: apitest
    database_user: bogdanvera
    database_password: null
    beanstalk_server: 127.0.0.1
    beanstalk_port: 11301
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt